### ISSUE TITLE
stringByURLEncoding behavior different in iOS 9

### ISSUE THREAD

**Issue by mohamedhafez** [Cocoanetics/DTFoundation#101]
In NSString+DTURLEncoding.m, the new code for stringByURLEncoding for > iOS 9 behaves very differently from the original code, which still being used for prior iOS versions: for prior versions all the characters in the string given are percent escaped, but for iOS 9, all special characters *EXCEPT* for the characters in the string given are percent escaped. (the string given is the same)

**Comment by odrobnik** [comment]
Please clarify why this is any issue.

**Comment by mohamedhafez** [comment]
on iOS 9, the behavior is the exact opposite  of what it is for iOS 8 and below, and what it has been in previous versions. if I try to url encode an email like "mohamed+hhh@gmail.com" (which is a valid email, gmail lets you add +<whatever> to any email you have), the + will be percent encoded in iOS 8, but won't in iOS 9.

**Comment by odrobnik** [comment]
@mohamedhafez I think you are misunderstanding what URL encoding means: it means to encode for use in URLs. A + is not a valid character in an URL since there this is a space.

**Comment by mohamedhafez** [comment]
Yeah exactly, if my email is mohamed+hhh@gmail.com (where I actually mean plus, not a space), and I want to encode that string for use in a URL, for example to pass to http://myserver.com/?email=...., then I need to percent encode the +, otherwise it'll be interpreted as a space and the server will see "mohamed hhh@gmail.com" instead of "mohamed+hhh@gmail.com"

**Comment by odrobnik** [comment]
I see... please send me a pull request with the corrected code.
