### ISSUE TITLE
Xcode 8 Beta 1 error

### ISSUE THREAD

**Issue by alistra** [Cocoanetics/DTFoundation#105]
`id impBlockForIMP = (__bridge id)objc_unretainedPointer(block);`

yields an error

"objc_unretainedPointer is unavailable, use a __bridge cast instead"

http://cl.ly/371z1k1y1y0K/Screen%20Shot%202016-06-14%20at%2011.30.18.png

**Comment by alistra** [comment]
This also happens on Beta 2.

I locally changed the line to compile my project to this:

`void (^impBlockForIMP)(id) = block;` 

Not sure if this satisfies your needs.

**Comment by odrobnik** [comment]
This should be addressed by #107

**Comment by alistra** [comment]
Yes, thank you. Please bump the cocoa pods version so we can `pod update` and have Xcode 8 working?

**Comment by bibobode** [comment]
Yes, @odrobnik, please.

**Comment by HoneyLuka** [comment]
@odrobnik Please~~~😀

**Comment by vittoriom** [comment]
Also please make a release for Carthage to work properly :)

**Comment by odrobnik** [comment]
@vittoriom What is necessary for Carthage releases?

**Comment by vittoriom** [comment]
Literally just a Github release 👍

**Comment by vittoriom** [comment]
And if you do it, please make sure to do one for DTCoreText too

**Comment by odrobnik** [comment]
Release done: https://www.cocoanetics.com/2016/09/dtfoundation-1-7-11/

**Comment by odrobnik** [comment]
Unfortunately there are problems limiting the pod spec for DTCoreText, as it is currently in master. Anybody have any ideas?
