### ISSUE TITLE
framework not found DTFoundation for architecture arm64

### ISSUE THREAD

**Issue by erdem-inan** [Cocoanetics/DTFoundation#109]
Hello,

I am using DTFoundation in a framework I am developing (using carthage). 
I am building my framework for arm64 architecture. But when I import my framework in a test project, and I try to build, I get this error:

ld: framework not found DTFoundation for architecture arm64

When a go in DTFoundation.framework I notice that there is not "DTFoundation.swiftmodule" directory in the "modules" directory. 
I also use other framework, and with the other framework there is all the time a directory "NAME_OF_FRAMEWORK.swiftmodule" with all the architecture supported.

is it normal ? could you help me with that ? Thanks

**Comment by odrobnik** [comment]
@erdem-inan I don't know how to help you. I have no experience with Carthage.
