### ISSUE TITLE
DTASN1 subspec does not support tvOS

### ISSUE THREAD

**Issue by jdrevet** [Cocoanetics/DTFoundation#117]
Hi,

I'd like to use features provided by DTASN1 on tvOS. Currently, I can't use DTFoundation/DTASN1 through Cocoapods because DTASN1 subspec does not declare support for tvOS. 
As the classes included in this subspec are included in the DTFoundation (tvOS) framework, I think that support could be added without problems.

**Comment by odrobnik** [comment]
@jdrevet I was thinking to do the same so that Kvitto can be used on tvOS via Cocoapods. Did you - by any change - try if DTASN1 can be compiled without issues?

**Comment by jdrevet** [comment]
Hi @odrobnik,

I have not made change to test compilation of DTASN1 on tvOS. But "DTFoundation (tvOS)" framework including DTASN1 files can be built without issues for tvOS simulator. I have also run pod lib lint after adding tvOS target for DTASN1 in podspec and it succeeds.

**Comment by jdrevet** [comment]
Hi @odrobnik,

Could you release a new version of the lib with the last commit ? In this way we can set this issue as resolved.

Regards

**Comment by odrobnik** [comment]
will release a maintenance update shortly
