### ISSUE TITLE
Core source errors and DTASN1Parser

### ISSUE THREAD

**Issue by rat-moonshine** [Cocoanetics/DTFoundation#118]
Hi there! 

I need some help with DTASN1Parser usage.

I became interested to this after reading how conveniently DTASN1Parser can decode certificates (https://www.cocoanetics.com/2012/02/parsing-asn-1-for-certificates-and-pleasure/).

I want this to be added in my Swift 3 iOS app, and so I copied complete 'Core' folder to my project. (Do you have any _pod_ install?) Once I copied the 'Core' folder I have been reported with tons of errors by XCode:

![screenshot](https://user-images.githubusercontent.com/24370870/37655182-9327db48-2c6a-11e8-9f15-8729e7aba865.png)

How can I fixed these errors and able to use DTASN1Parser in my app (?) Is there any working demo available for DTASN1Parser (?)

Any help would be good. 

Thanks!

**Comment by odrobnik** [comment]
If you want to use the source files for the parser by themselves you have to make a lot of changes. Better to to use the framework as a cocoa pod or git submodule.
