### ISSUE TITLE
SPM: Some Categories not visible

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/DTFoundation#127]
I am looking for an explanation and/or fix why category extensions in `UIView+DTFoundation.h/m` cannot be used when importing this Package via SPM

**Comment by colejd** [comment]
For what it's worth, the issue I ran into was only at runtime. It was not detected at build time.

**Comment by odrobnik** [comment]
@colejd please explain.

**Comment by odrobnik** [comment]
The file is definitely part of the Package:

![image](https://user-images.githubusercontent.com/333270/93556107-29bf0e00-f978-11ea-9a5c-73aad1b13507.png)

It even gets compiled:

![image](https://user-images.githubusercontent.com/333270/93556098-2166d300-f978-11ea-9bc9-2f7117af354f.png)

But seemingly all the UIKit-based extensions are missing:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/333270/93556078-1318b700-f978-11ea-8d79-85e27a72d59b.png">

Although, some are there, like NSURL+DTAppLinks which is also in the same Core/Source/iOS subfolder:

```let bla = NSURL.appStoreReview(forApplicationIdentifier: "123")```

This works.

**Comment by odrobnik** [comment]
I found that adding `#import <TargetConditionals.h>` to the header and moving the import for the header in the .m to above the `#if TARGET_OS_IPHONE` resolved the problem.

It might be that adding these defines manually to the Package file doesn't always work, and the import in the PCH file seems to be ignored for Packages.

**Comment by colejd** [comment]
Thanks. That seems to have done the trick on my end.

The runtime issues I mentioned earlier seem to be internal to DTCoreText, so I've made a new issue above.
