### ISSUE TITLE
Please update podspec to 1.7.18, and publish it.

### ISSUE THREAD

**Issue by SuperY** [Cocoanetics/DTFoundation#134]
It does not work when I use DTCoreText 1.6.26 through Cocoapods.

**Comment by odrobnik** [comment]
Sorry, I don't understand. Do you mean that I should update the required version of DTFoundation in the DTCoreText podspec?

**Comment by SuperY** [comment]
> Sorry, I don't understand. Do you mean that I should update the required version of DTFoundation in the DTCoreText podspec?

No，I did know DTCoreText has update the DTFoundation dependency version.

But DTFoundation's podspac file not update version. And need publish new podspac to Cocoapods repo.

**Comment by odrobnik** [comment]
What do you mean by that. It's not released yet on Cocoapods. For that I need to push both to trunk.

**Comment by SuperY** [comment]
> What do you mean by that. It's not released yet on Cocoapods. For that I need to push both to trunk.

Sorry, I thought DTCoreText was released. I'll wait

**Comment by odrobnik** [comment]
I've published the updates for DTFoundation and DTCoreText, that should fix your issue.
