### ISSUE TITLE
Xcode 13 beta 4 - SwiftPackageManager error App Extensions

### ISSUE THREAD

**Issue by Gharib-sara** [Cocoanetics/DTFoundation#135]
Hi,

`DTFoundation` is not building anymore with the new Xcode using SPM

<img width="1170" alt="Screenshot 2021-08-09 at 15 40 33" src="https://user-images.githubusercontent.com/70710022/128715704-2735954a-c199-43da-86e9-9e97fe8e07d3.png">

It may be related to this update: 

- Linking Swift packages from application extension targets or watchOS applications no longer emits unresolvable warnings about linking to libraries not safe for use in application extensions. This means that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application extensions, in order to allow that code to be used in both apps and app extensions.

    **Source**: https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes

**Comment by odrobnik** [comment]
Why would you compile DTFoundation for an app extension?

**Comment by Gharib-sara** [comment]
I don't have any app extensions linked to my project.

**Comment by odrobnik** [comment]
I didn't have any problems compiling with Xcode 13 beta 5. I tried both `swift build` in the project root, as well as adding DTFoundation as a package reference in a new project.

**Comment by Gharib-sara** [comment]
Yes, it seems to be working fine with Beta 5. Thanks
