### ISSUE TITLE
1.7.4 Changelog?

### ISSUE THREAD

**Issue by rsanchezsaez** [Cocoanetics/DTFoundation#88]
Sorry for creating an issue about this. Any summarized up 1.7.4 changelog? Thanks for your great work!

**Comment by Cocoanetics** [comment]
see for example here: https://github.com/Cocoanetics/DTFoundation/releases

**Comment by rsanchezsaez** [comment]
Thanks!

I didn't see it [here](https://github.com/Cocoanetics/DTFoundation/blob/develop/Documentation/Change%20Log-template.markdown) so I wrongly assumed it was not anywhere.

Cheers.
