### ISSUE TITLE
Using DTFolderMonitor to get changes in directory

### ISSUE THREAD

**Issue by dominik0711** [Cocoanetics/DTFoundation#98]
Hi. Is it possible to retrieve the corresponding action (deleted, added, renamed) and filePath in a monitored folder using DTFolderMonitor? The callback only reports that something has changed.
If yes, could you please provide sample code or give me a hint how to implemented such behaviour?

I need the following action:

  - file added
  - file removed/deleted
  - file renamed (from -> to)

Thanks in advance

**Comment by odrobnik** [comment]
The easiest would probably be to implement a class that has a directory listing and then whenever DTFolderMonitor reports that something changed, get a new listing and compare the new and old.
