### ISSUE TITLE
Cocoapods 1.0.0 beta 2

### ISSUE THREAD

**Issue by m1entus** [Cocoanetics/DTFoundation#99]
Each time when i make pod install, i have error: 
<img width="360" alt="zrzut ekranu 2016-01-25 o 23 47 02" src="https://cloud.githubusercontent.com/assets/1565368/12567196/130c7ed0-c3be-11e5-8d4a-f3b253f54aaf.png"> only in DTFoundation. After cleaning project, everything is compiling fine... :/ Any ideas why ?

**Comment by odrobnik** [comment]
Unable to reproduce this issue with the current version of the develop branch.
